name: docker-build

on:
  push:
    branches:
      - "main"
      - "app"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: bweng/app:latest
          cache-from: type=registry,ref=bweng/app:latest
          cache-to: type=inline